config/routes.rb
Plumber::Engine.routes.draw do
  resources :campaigns, only: [:index, :show]
  resources :messages, only: :show
end

app/models/plumber/application_record.rb
module Plumber
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/plumber/campaign.rb
module Plumber
  class Campaign
    include ActiveModel::Model

    attr_accessor :id, :title, :record_class, :delay_column, :filter, :messages, :start_sending, :stop_sending

    def self.all
      Repo.list_campaigns
    end

    def self.find(id)
      Repo.get_campaign(id)
    end

    def self.send!(as_of = Time.current)
      all.each do |campaign|
        campaign.send_messages(as_of)
      end
    end

    def send_messages(as_of = Time.current)
      start_time = as_of.change(hour: start_sending, min: 0, sec: 0)
      stop_time  = as_of.change(hour: stop_sending, min: 0, sec: 0)
      return unless as_of >= start_time && as_of <= stop_time
      active_messages.each do |message|
        records_to_send(as_of, message).each do |record|
          SentMessage.find_or_create_by(record: record, message_id: message.id)
        end
      end
    end

    def records_to_send(as_of, message)
      target_date = as_of.to_date - message.delay.days
      # Look back 1 hour to make sure we catch records close to cutoff
      start = target_date.yesterday.noon.change(hour: stop_sending - 1, min: 0, sec: 0)
      stop  = target_date.noon.change(hour: as_of.hour, min: as_of.min, sec: as_of.sec)
      records.where("#{record_table}.#{delay_column} > ?", start)
             .where("#{record_table}.#{delay_column} <= ?", stop)
    end

    def upcoming_records
      return records unless messages.any?
      target_date = Date.current.to_date - delays.max.days
      start = target_date.yesterday.noon.change(hour: stop_sending, min: 0, sec: 0)
      records.where("#{record_table}.#{delay_column} > ?", start)
    end

    def records
      model.ransack(filter).result
    end

    def delays
      messages.map(&:delay)
    end

    def messages=(array)
      @messages = array.map { |e| m = Message.new(e); m.campaign = self; m }
    end

    def active_messages
      messages.select { |m| m.active }
    end

    def slug
      title.parameterize
    end

    def start_sending
      @start_sending ||= 0
    end

    def stop_sending
      @stop_sending ||= 24
    end

    private

      def model
        @model ||= record_class.safe_constantize
      end

      def record_table
        model.table_name
      end
  end
end

app/models/plumber/message.rb
module Plumber
  class Message
    include ActiveModel::Model

    attr_accessor :id, :campaign, :from, :subject, :template, :delay, :active

    alias_method :active?, :active

    def self.find(id)
      Repo.get_message(id)
    end

    def initialize(attrs = {})
      attrs = attrs.with_indifferent_access
      self.id = attrs[:id]
      self.from = attrs[:from] if attrs[:from]
      self.subject = attrs[:subject]
      self.template = attrs[:template]
      self.delay = attrs[:delay]
      self.active = attrs[:active]
      self.campaign = Campaign.new(attrs[:campaign]) if attrs[:campaign]
    end

    def parsed_template
      @parsed_template ||= Liquid::Template.parse(template)
    end

    def html(record)
      parsed_template.render(record.to_h.deep_stringify_keys)
    end

    def from
      @from ||= Plumber.email_from
    end
  end
end

app/models/plumber/sent_message.rb
module Plumber
  class SentMessage < ApplicationRecord
    belongs_to :record, polymorphic: true

    before_create :deliver_message, on: :create

    private

      def deliver_message
        return unless record.email.present?
        self.email = record.email
        NotificationMailer.send_message(
          record: record,
          message_id: message_id
        ).deliver_later
      end
  end
end

app/controllers/plumber/application_controller.rb
module Plumber
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

app/controllers/plumber/campaigns_controller.rb
require_dependency "plumber/application_controller"

module Plumber
  class CampaignsController < ApplicationController
    # GET /campaigns
    def index
      @campaign = Campaign.all.first
      @records = @campaign.upcoming_records.page(params[:page]) if @campaign
      render @campaign ? :show : :index
    end

    # GET /campaigns/1
    def show
      @campaign = Campaign.find(params[:id])
      @records = @campaign.upcoming_records.page(params[:page])
    end
  end
end

app/controllers/plumber/messages_controller.rb
require_dependency "plumber/application_controller"

module Plumber
  class MessagesController < ApplicationController
    # GET /messages/1
    def show
      @message = Message.find(params[:id])
      @campaign = @message.campaign
      @sent_messages = SentMessage.where(message_id: @message.id).page(params[:page])
    end
  end
end

app/helpers/plumber/application_helper.rb
module Plumber
  module ApplicationHelper
  end
end

app/helpers/plumber/campaigns_helper.rb
module Plumber
  module CampaignsHelper
    def twelve_hour(hour)
      if hour == 0
        "Beginning of day"
      elsif hour == 24
        "End of day"
      elsif hour <= 12
        "#{hour}am"
      else
        "#{hour - 12}pm"
      end
    end
  end
end

app/helpers/plumber/messages_helper.rb
module Plumber
  module MessagesHelper
  end
end

app/views/layouts/plumber/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Apply</title>
    <%= tag(:meta, charset: 'utf-8') %>
    <%= tag(:meta, name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'plumber/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'plumber/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render Plumber.nav_partial || "navigation" %>
    <%= render "flashes" %>

    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/plumber/application/_flashes.html.erb
<p class="flash notice"><%= notice %></p>
<p class="flash alert"><%= alert %></p>

app/views/plumber/application/_navigation.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <%= link_to "Align", Plumber.brand_link, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Campaigns", campaign_path(Plumber::Campaign.all.first.slug), class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/plumber/campaigns/_subnav.html.erb
<div class="list-group my-2">
  <% Plumber::Campaign.all.each do |campaign| %>
    <%= link_to campaign.title, campaign_path(campaign.id), class: "list-group-item" %>
  <% end %>
</div>

app/views/plumber/campaigns/index.html.erb
<div class="py-5">
  <h3 class="text-center">
    You have not defined any campaigns.
  </h3>
</div>

app/views/plumber/campaigns/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= render "subnav" %>
  </div>
  <div class="col-sm-9">
    <h1><%= @campaign.title %></h1>

    <p>Send from <%= twelve_hour @campaign.start_sending %> to <%= twelve_hour @campaign.stop_sending %></p>

    <div class="card mb-3">
      <h5 class="card-header">
        Matching <%= @campaign.record_class.pluralize %>
      </h5>
      <div class="card-body">
        <% @campaign.filter.each do |k, v| %>
          <div class="btn btn-light">
            <code><%= k %> <%= v %></code>
          </div>
        <% end %>
      </div>
      <ul class="list-group list-group-flush">
        <% @records.each do |record| %>
          <li class="list-group-item">
            <%= record.email %>
          </li>
        <% end %>
      </ul>
    </div>

    <%= paginate @records, theme: "twitter-bootstrap-4" %>

    <div class="card mb-3">
      <h5 class="card-header">
        Campaign Messages
      </h5>
      <div class="list-group list-group-flush">
        <% @campaign.messages.each do |message| %>
          <%= link_to message_path(message.id), class: "list-group-item" do %>
            <%= message.subject %> -
            day <%= message.delay %>
            (<%= message.active? ? 'active' : 'inactive' %>)
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/plumber/messages/show.html.erb
<div class="row">
  <div class="col-sm-3">
    <%= render "plumber/campaigns/subnav" %>
  </div>
  <div class="col-sm-9">
    <h1><%= link_to @campaign.title, campaign_path(@campaign.id) %></h1>

    <div class="card mb-3">
      <h5 class="card-header">
        <%= @message.subject %>
      </h5>
      <div class="card-body">
        <p>
          <strong>Delay:</strong>
          <%= @message.delay %> days based on <code><%= @campaign.delay_column %></code>
          <% if @message.active? %>
            <span class="badge badge-pill badge-success float-right">Active</span>
          <% else %>
            <span class="badge badge-pill badge-danger float-right">Inactive</span>
          <% end %>
        </p>
        <p>
          <strong>From:</strong> <%= @message.from %>
        </p>
        <hr>
        <%= Kramdown::Document.new(@message.template).to_html.html_safe %>
      </div>
    </div>

    <div class="card">
      <h5 class="card-header">
        Sends
      </h5>
      <ul class="list-group list-group-flush">
        <% @sent_messages.each do |sent_message| %>
          <li class="list-group-item"><%= sent_message.email %> @ <%= sent_message.created_at %></li>
        <% end %>
      </ul>
    </div>

    <%= paginate @sent_messages, theme: "twitter-bootstrap-4" %>
  </div>
</div>